import { Inter, Onest } from 'next/font/google';
import './globals.css';
import Providers from './provider';
import Navbar from '@/components/common/navbar';

const inter = Onest({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main> {children}</main>
        </Providers>
      </body>
    </html>
  );
}
