export const navbarMenu = [
  {
    id: 'home',
    label: 'Home',
    link: '/',
  },
  {
    id: 'find-a-pet',
    label: 'Find a pet',
    link: '/pets',
  },
  {
    id: 'list-a-pet',
    label: 'List a pet',
    link: '/add-pet',
  },
  // {
  //   id: 'organizations',
  //   label: 'Organizations',
  //   link: '/organizations',
  // },
];

export const petListData = [
  {
    id: 1,
    name: 'Dummy Dog',
    species: 'Dog',
    breed: 'Pug',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '4 yr',
    gender: 'Male',
    description: 'dog is so beautiful',
    breed: 'Mixed Breed / Moggie',
    color: 'White, Red/Ginger',
    reason: 'Change in family circumstances',
  },
  {
    id: 2,
    name: 'Whiskers Cat',
    species: 'Cat',
    breed: 'Siamese',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '1.5 yr',
    gender: 'Female',
    description: 'Graceful Siamese cat with blue eyes.',
    color: 'Cream',
    reason: 'Owners allergies',
  },
  {
    id: 3,
    name: 'Hopper Rabbit',
    species: 'Rabbit',
    breed: 'Dutch',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '1 yr',
    gender: 'Male',
    description: 'Cute bunny with a playful personality.',
    color: 'White and Black',
    reason: 'Moving to a pet-free apartment',
  },
  {
    id: 4,
    name: 'Cleo Snake',
    species: 'Snake',
    breed: 'Ball Python',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '2 yr',
    gender: 'Female',
    description: 'Gentle Ball Python with striking patterns.',
    color: 'Brown and Gold',
    reason: 'Owners changed interests',
  },
  {
    id: 5,
    name: 'Tweety Bird',
    species: 'Bird',
    breed: 'Canary',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '2.5 yr',
    gender: 'Male',
    description: 'Singing canary with a bright yellow plumage.',
    color: 'Yellow',
    reason: 'Owners busy schedule',
  },
  {
    id: 6,
    name: 'Shadow Hamster',
    species: 'Hamster',
    breed: 'Syrian',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '6 months',
    gender: 'Female',
    description: 'Active hamster with a sleek black coat.',
    color: 'Black',
    reason: 'Owners time constraints',
  },
  {
    id: 7,
    name: 'Gizmo Ferret',
    species: 'Ferret',
    breed: 'Sable',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '1 yr',
    gender: 'Male',
    description: 'Playful ferret with a mischievous streak.',
    color: 'Brown',
    reason: 'Owners health issues',
  },
  {
    id: 8,
    name: 'Mittens Turtle',
    species: 'Turtle',
    breed: 'Red-Eared Slider',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '5 yr',
    gender: 'Unknown',
    description: 'Easygoing turtle that enjoys basking.',
    color: 'Green and Yellow',
    reason: 'Family allergy concerns',
  },
  {
    id: 9,
    name: 'Rusty Guinea Pig',
    species: 'Guinea Pig',
    breed: 'Abyssinian',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '1.5 yr',
    gender: 'Male',
    description: 'Adorable guinea pig with a rusty-colored coat.',
    color: 'Rust',
    reason: 'Owners relocation',
  },
  {
    id: 10,
    name: 'Smokey Horse',
    species: 'Horse',
    breed: 'Quarter Horse',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '8 yr',
    gender: 'Female',
    description: 'Gentle and strong Quarter Horse.',
    color: 'Gray',
    reason: 'Change in owners lifestyle',
  },
  {
    id: 11,
    name: 'Patches Chinchilla',
    species: 'Chinchilla',
    breed: 'Standard Gray',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '2.5 yr',
    gender: 'Female',
    description: 'Soft and furry chinchilla with unique markings.',
    color: 'Gray and White',
    reason: 'Owners new job with long hours',
  },
  {
    id: 12,
    name: 'Leo Lizard',
    species: 'Lizard',
    breed: 'Bearded Dragon',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '1 yr',
    gender: 'Male',
    description: 'Colorful bearded dragon with vibrant scales.',
    color: 'Orange and Yellow',
    reason: 'Owners personal reasons',
  },
  {
    id: 13,
    name: 'Sasha Fish',
    species: 'Fish',
    breed: 'Betta',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '1.5 yr',
    gender: 'Female',
    description: 'Beautiful Betta fish with flowing fins.',
    color: 'Blue and Red',
    reason: 'Owners focus on other hobbies',
  },
  {
    id: 14,
    name: 'Mocha Ferret',
    species: 'Ferret',
    breed: 'Chocolate',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '1 yr',
    gender: 'Female',
    description: 'Sweet ferret with a rich chocolate-colored coat.',
    color: 'Brown',
    reason: 'Family members allergy',
  },
  {
    id: 15,
    name: 'Oreo Rabbit',
    species: 'Rabbit',
    breed: 'Dwarf Hotot',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '1.5 yr',
    gender: 'Male',
    description: 'Cute dwarf rabbit with distinctive black and white markings.',
    color: 'Black and White',
    reason: 'Owners new living situation',
  },
  {
    id: 16,
    name: 'Misty Parrot',
    species: 'Bird',
    breed: 'African Grey',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '4 yr',
    gender: 'Unknown',
    description: 'Intelligent African Grey parrot with a gray plumage.',
    color: 'Gray',
    reason: 'Owners relocation to a non-pet-friendly place',
  },
  {
    id: 17,
    name: 'Max Turtle',
    species: 'Turtle',
    breed: 'Painted Turtle',
    links: [
      'https://hips.hearstapps.com/hmg-prod/images/dog-puppy-on-garden-royalty-free-image-1586966191.jpg',
      'https://images.lifestyleasia.com/wp-content/uploads/sites/7/2021/03/02155402/photo-1610575828349-43f195e95452.jpeg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hsWm50KxX_Hs1BBsFLAVeFuUhkeKXH_Hu-GjLSkkqX2Ne1dsQh1qxnHIGE-VTc8UVlk&usqp=CAU',
    ],
    age: '3 yr',
    gender: 'Unknown',
    description: 'Painted turtle with vibrant shell patterns.',
    color: 'Multi-colored',
    reason: 'Familys decision to downsize',
  },
];
